# Generated by Django 4.2.4 on 2023-08-20 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='photos_sec',
        ),
    ]
