# Generated by Django 4.2.4 on 2023-08-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pets', '0003_alter_pets_health_detail_alter_pets_pers_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='qr_donation',
            field=models.ImageField(blank=True, upload_to='shelter_logos/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shelter_description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shelter_logo',
            field=models.ImageField(blank=True, upload_to='qr_donations/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shelter_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
